### ISSUE TITLE
./check_BADGE.sh fails on Ubuntu 18.04 and WSL Ubuntu 18.04 & 16.04

### ISSUE THREAD

**Issue by muecker** [TMW-bioinformatics/BADGE#1]
Hey,
I I tried to run BADGE on the test data set to see if my installation works properly. 
The following error occurred for the search of B and C specific DMGs (for A it worked just fine):
```
#######################################################################
Step 3 of 6:  MEGABLAST B DMGs orfs vs all single B orfs - Occurrence filter B DMGs

awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted in `%'
Command line argument error: Argument "query". File is not accessible:  `./seq_split*.fasta'
Number of DMGs after occurrence filter: 2.

#######################################################################
Step 4 of 6:  DC-MEGABLAST B DMGs vs A genomes - DC filter B DMGs

awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted in `%'
Command line argument error: Argument "query". File is not accessible:  `./seq_split*.fasta'
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted in `%'
Command line argument error: Argument "query". File is not accessible:  `./seq_split*.fasta'
Number of DMGs after dc_megablast filter: 2.

#######################################################################
Step 5 of 6:  BLASTN B DMGs vs A genome sequences - BLASTN filter B DMGs

awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted in `%'
Command line argument error: Argument "query". File is not accessible:  `./seq_split*.fasta'
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted in `%'
Command line argument error: Argument "query". File is not accessible:  `./seq_split*.fasta'
Number of DMGs after blastn filter: 0.

#######################################################################
Step 6 of 6:  Create BADGE output

Command line argument error: Argument "query". File is not accessible:  `./seq_split*.fasta'
Command line argument error: Argument "query". File is not accessible:  `./seq_split*.fasta'
Command line argument error: Argument "query". File is not accessible:  `./seq_split*.fasta'
Command line argument error: Argument "query". File is not accessible:  `./seq_split*.fasta'
../BADGE.sh: line 2178: BADGE_B_vs_A_DMGs_new.annotation: No such file or directory
mv: cannot stat 'BADGE_B_vs_A_DMGs_tmp.fasta': No such file or directory
Command line argument error: Query is Empty!
Command line argument error: Query is Empty!

All files moved to corresponding directory
```

I have tried to run the programme on Ubuntu 18.04 and the WSL (Ubuntu 18.04 & Ubuntu 16.04), always with a freshly downloaded and unzipped folder without any changes to the files and folders. However, I always experience the same error. 
Have you experienced this before? Did BADGE run succesfully for you on newer Ubuntu versions (I could only find information about it running successfully on Ubuntu 14.04)?

I hope you can help me sort this out as your programme promises all functions that I need.

Best,
Merle
[fail_report.tar.gz](https://github.com/TMW-bioinformatics/BADGE/files/4170231/fail_report.tar.gz)

**Comment by TMW-bioinformatics** [comment]
Dear Merle,
you are right, I could reproduce your error on Ubuntu 18.04 & Ubuntu 16.04. I am not yet sure why we have this issue here and not on Ubuntu 14.04. The problem comes from the rare occasion that we have less sequences to blast than configured blast processes. In principle the script should handle this. I will try to fix this in the next release.

For now you could try this quick fix:
in BADGE.sh

change line 54:
`num_blast_proc=4`
to 
`num_blast_proc=1`
then try if check_BADGE.sh works now correct.

Best,
Juergen.
